--0)
alter system flush buffer_cache;
alter system flush shared_pool;

--2)
CREATE TABLE TESTE_10(
  id NUMBER,
  nome1 VARCHAR2(2000),
  nome2 VARCHAR2(2000),
  CONSTRAINT PK_Teste10 PRIMARY KEY(id)
);

CREATE TABLE TESTE_10_COM_INDICE(
  id NUMBER,
  nome1 VARCHAR2(2000),
  nome2 VARCHAR2(2000),
  CONSTRAINT PK_Teste10ComIndice PRIMARY KEY(id)
);

CREATE INDEX INDEX_nome1
ON TESTE_10_COM_INDICE(nome1);

CREATE BITMAP INDEX INDEX_nome2
ON TESTE_10_COM_INDICE(nome2);

--3)
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10'', 10); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10_COM_INDICE'', 10); END;');
END;
/

--4)
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10'', 10); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10_COM_INDICE '', 10); END;');
END;
/
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10'', 10); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10_COM_INDICE '', 10); END;');
END;
/

--5)
--100 Tuplas
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10'', 100); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10_COM_INDICE'', 100); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10'', 100); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10_COM_INDICE '', 100); END;');
END;
/
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10'', 100); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10_COM_INDICE '', 100); END;');
END;
/

--1000 Tuplas
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10'', 1000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10_COM_INDICE'', 1000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10'', 1000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10_COM_INDICE '', 1000); END;');
END;
/
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10'', 1000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10_COM_INDICE '', 1000); END;');
END;
/

--10000 Tuplas
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10'', 10000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10_COM_INDICE'', 10000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10'', 10000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10_COM_INDICE '', 10000); END;');
END;
/
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10'', 10000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10_COM_INDICE '', 10000); END;');
END;
/

--100000 Tuplas
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10'', 100000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10_COM_INDICE'', 100000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10'', 100000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10_COM_INDICE '', 100000); END;');
END;
/
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10'', 100000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10_COM_INDICE '', 100000); END;');
END;
/

--1000000 Tuplas
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10'', 1000000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
 GETTIME('DECLARE BEGIN INSERT_INTO(''TESTE_10_COM_INDICE'', 1000000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10'', 1000000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BTREE(''TESTE_10_COM_INDICE '', 1000000); END;');
END;
/
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10'', 1000000); END;');
END;
/
set serveroutput on;
DECLARE
BEGIN
  GETTIME('DECLARE BEGIN SELECT_FROM_BITMAP(''TESTE_10_COM_INDICE '', 1000000); END;');
END;
/